import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
  title: "SYM",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar/>

        {children}

        <footer
          style={{
            textAlign:"center"
          }}
        >
          <p className=" bg-gray-500 text-gray-800 text-xl">Footer</p>
        </footer>
      </body>
    </html>
  );
}
